server:
   port: 7900
spring:
   jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
         ddl-auto: none
   datasource:
      platform: h2
      schema: classpath:schema.sql
      data: classpath:data.sql
   application:
      name: provider-user
logging:
   level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
      com.itmuch: DEBUG
#eureka客户端连接配置
eureka:
   client:
      #开启健康检查
      healthcheck:
         enabled: true
      service-url:
      #注册中心地址
         defaultZone: http://user:password123@localhost:8761/eureka
   instance:
      #将ip注册到eureka上
      prefer-ip-address: true
      #微服务向eureka注册实例名${spring.cloud.client.ip-address} 表示ip地址
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}