---
server:
   port: 8761
#安全认证配置
spring:
   application:
      name: EUREKA-HA
   security:
      basic:
         enabled: true
      user:
         name: user
         password: password123
eureka:
   #Eureka实例名，集群中根据这里相互识别
   instance:
      hostname: peer1
   client:
      serviceUrl:
         #注册中心地址
         defaultZone: http://user:password123@peer2:8762/eureka/,http://user:password123@peer3:8763/eureka/
---
server:
   port: 8762
#安全认证配置
spring:
   application:
      name: EUREKA-HA
   security:
      basic:
         enabled: true
      user:
         name: user
         password: password123
eureka:
   #Eureka实例名，集群中根据这里相互识别
   instance:
      hostname: peer2
   client:
      serviceUrl:
         defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer3:8763/eureka/
---
server:
   port: 8763
#安全认证配置
spring:
   application:
      name: EUREKA-HA
   security:
      basic:
         enabled: true
      user:
         name: user
         password: password123
eureka:
   #Eureka实例名，集群中根据这里相互识别
   instance:
      hostname: peer3
   client:
      serviceUrl:
         defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/