server:
  port: 8011
  #增加context-path访问路径   地址变为  http://localhost:8011/ribbon/movie/1
  servlet:
     context-path: /ribbon
spring:
  application:
      name: consumer-movie-ribbon-with-hystrix2
#eureka客户端连接配置
eureka:
   client:
      healthcheck:
         enabled: true
      service-url:
      #注册中心地址
         defaultZone: http://user:password123@localhost:8761/eureka
   instance:
      #将ip注册到eureka上
      prefer-ip-address: true
      #微服务向eureka注册实例名${spring.cloud.client.ip-address} 表示ip地址 spring2.0以上为ip-address
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
      #修改home-page-url-path告诉eureka更改homepageUrlPath路径为 localhost:8011/ribbon
      home-page-url-path: /ribbon
#开放health,info,hystrix.stream页面路径访问 http://localhost:8011/actuator/hystrix.stream
management: 
  endpoints: 
    web: 
      exposure: 
        include: health,info,hystrix.stream #根据需求增删路径