server:
   port: 8030
spring:
   application:
      name: springcloud-hystrix-turbine3
#eureka相关配置
eureka:
   client:
      service-url:
         defaultZone: http://user:password123@localhost:8761/eureka
   instance:
      prefer-ip-address: true
#Turbine相关配置
turbine:
   aggregator:
      clusterConfig: CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX3
   appConfig: consumer-movie-ribbon-with-hystrix3
#显示日志
logging: 
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG